routes/web.php
<?php

declare(strict_types=1);

use App\Http\Controllers\Employee\PostController as EmployeePostController;
use App\Http\Controllers\User\PostController as UserPostController;
use App\Http\Controllers\User\ProfileController;
use Illuminate\Support\Facades\Route;

include 'auth.php';

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth:employee'], function () {
    Route::resource('posts', EmployeePostController::class);
    Route::get('refresh-image/{id}', [EmployeePostController::class, 'refreshImage'])->name('posts.refresh_image');
});

Route::group(['middleware' => 'auth:web'], function () {
    Route::get('/', [UserPostController::class, 'index'])->name('posts.index');
    Route::get('posts/{id}', [UserPostController::class, 'show'])->name('posts.show');
    Route::resource('profile', ProfileController::class)->only(['index', 'update', 'destroy']);
});

app/Models/Employee.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * @property int $id
 * @property string $email
 */
class Employee extends Authenticatable
{
    use HasFactory;

    protected $fillable = [
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'password' => 'hashed',
    ];
}

app/Models/Post.php
<?php

declare(strict_types=1);

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property int $id
 * @property string $title
 * @property ?string $image
 * @property ?string $text
 * @property ?Carbon $deleted_at
 */
class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $perPage = 10;

    protected $fillable = [
        'title',
        'text',
        'image',
    ];
}

app/Models/User.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * @property int $id
 * @property string $name
 * @property ?string $avatar
 * @property string $email
 */
class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'avatar',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/Employee/PostController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\Controller;
use App\Http\Requests\Employee\StorePostRequest;
use App\Http\Requests\Employee\UpdatePostRequest;
use App\Services\EmployeePostService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class PostController extends Controller
{
    public function __construct(private readonly EmployeePostService $employeePostService)
    {
    }

    public function index(): View
    {
        $posts = $this->employeePostService->getPosts();

        return view('employee.posts.index', compact('posts'));
    }

    public function create(): View
    {
        return view('employee.posts.create');
    }

    public function store(StorePostRequest $request): RedirectResponse
    {
        $this->employeePostService->createPost($request->input('title'), $request->input('text'));

        return redirect()->route('admin.posts.index');
    }

    public function show(int $id): View
    {
        $post = $this->employeePostService->showPost($id);

        return view('employee.posts.show', compact('post'));
    }

    public function refreshImage(int $id): RedirectResponse
    {
        $this->employeePostService->refreshImage($id);

        return redirect()->route('admin.posts.edit', $id);
    }

    public function edit(int $id): View
    {
        $post = $this->employeePostService->showPost($id);

        return view('employee.posts.edit', compact('post'));
    }

    public function update(UpdatePostRequest $request, int $id): RedirectResponse
    {
        $this->employeePostService->updatePost($id, $request->input('title'), $request->input('text'));

        return back();
    }

    public function destroy(int $id): RedirectResponse
    {
        $this->employeePostService->deletePost($id);

        return back();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/User/PostController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Services\UserPostService;
use Illuminate\Contracts\View\View;

class PostController extends Controller
{
    public function __construct(private readonly UserPostService $userPostService)
    {
    }

    public function index(): View
    {
        $posts = $this->userPostService->getPosts();

        return view('user.posts.index', compact('posts'));
    }

    public function show(int $id): View
    {
        $post = $this->userPostService->showPost($id);

        return view('user.posts.show', compact('post'));
    }
}

app/Http/Controllers/User/ProfileController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\UpdateProfileRequest;
use App\Services\UserProfileService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ProfileController extends Controller
{
    public function __construct(private readonly UserProfileService $userProfileService)
    {
    }

    public function index(): View
    {
        $user = $this->userProfileService->getProfile();

        return view('user.profile.show', compact('user'));
    }

    public function update(UpdateProfileRequest $request, int $id): RedirectResponse
    {
        $this->userProfileService->updateProfile($request, $id);

        return back();
    }

    public function destroy(int $id): RedirectResponse
    {
        $this->userProfileService->deleteProfile();

        return redirect()->route('home');
    }
}

resources/views/employee/posts/create.blade.php
@extends('layouts.employee_app')

@section('title', 'Create Post')

@php
    use App\Models\Post;
    /** @var Post $post */
@endphp

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-8">
                <h1>@yield('title')</h1>

                <div class="card">
                    {{ html()->form()->route('admin.posts.store')->open() }}

                    <div class='col-6 mb-3'>
                        @if ($errors->has('title'))
                            <span class="text-danger">{{ $errors->first('title') }}</span>
                        @endif
                        <label class="form-label" for="title">title</label>
                        {{ html()->input('text', 'title')->id('title')->class('form-control form-control') }}
                    </div>


                    <div class='mb-3'>
                        @if ($errors->has('text'))
                            <span class="text-danger">{{ $errors->first('text') }}</span>
                        @endif
                        <label class="form-label" for="text">text</label>
                        {{ html()->textarea('text')->id('text')->class('form-control form-control') }}
                    </div>

                    <div class='col-12 d-flex justify-content-end'>
                        <button type="submit">Create</button>
                    </div>


                    {{ html()->form()->close() }}

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employee/posts/edit.blade.php
@extends('layouts.employee_app')

@section('title', 'Edit Post')

@php
    use App\Models\Post;
    /** @var Post $post */
@endphp

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('components.employee.nav')

            <div class="col-md-8">
                <h1>@yield('title')</h1>

                <div class="card">
                    <img width="100" src="{{$post->image}}" alt="">
                    <a href="{{route('admin.posts.refresh_image', $post->id)}}">randomize image</a>

                    {{ html()->form('PUT')->route('admin.posts.update', $post->id)->open() }}

                    <div class='col-6 mb-3'>
                        @if ($errors->has('title'))
                            <span class="text-danger">{{ $errors->first('title') }}</span>
                        @endif
                        <label class="form-label" for="title">title</label>
                        {{ html()->input('text', 'title', $post->title)->id('title')->class('form-control form-control') }}
                    </div>


                    <div class='mb-3'>
                        @if ($errors->has('text'))
                            <span class="text-danger">{{ $errors->first('text') }}</span>
                        @endif
                        <label class="form-label" for="text">text</label>
                        {{ html()->textarea('text', $post->text)->id('text')->class('form-control form-control') }}
                    </div>

                    <div class='col-12 d-flex justify-content-end'>
                        <button type="submit">Update</button>
                    </div>

                    {{ html()->form()->close() }}

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employee/posts/index.blade.php
@extends('layouts.employee_app')

@php
    use App\Models\Post;
    /** @var Post $post */
@endphp

@section('content')
    <div class="container">
        @include('components.employee.nav')

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    @forelse($posts as $post)
                        <a href="{{route('posts.show', $post->id)}}"><h3>{{$post->title}}</h3></a>
                        <img width="100" src="{{$post->image}}" alt="">

                        <a href="{{route('admin.posts.edit', $post->id)}}">edit</a>
                        @if(false === is_null($post->deleted_at))
                            <span class="text-danger">[DELETED]</span>
                        @else
                            {{ html()->form('DELETE')->route('admin.posts.destroy', $post->id)->open() }}
                            <input type="submit" class="btn-sm" value="Delete">
                            {{ html()->form()->close() }}
                        @endif
                        <hr>
                    @empty
                        empty
                    @endforelse

                    {{$posts->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
@include('components.head')
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/employee_app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
@include('components.head')

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('admin.login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/user/posts/index.blade.php
@extends('layouts.app')

@php
    use App\Models\Post;
    /** @var Post $post */
@endphp

@section('content')
    <div class="container">
        @include('components.user.nav')
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    @forelse($posts as $post)
                        <a href="{{route('posts.show', $post->id)}}"><h3>{{$post->title}}</h3></a>
                        <img width="100" src="{{$post->image}}" alt="">
                    @empty
                        empty
                    @endforelse

                    {{$posts->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/posts/show.blade.php
@extends('layouts.app')

@php
    use App\Models\Post;
    /** @var Post $post */
@endphp

@section('content')
    <div class="container">
        @include('components.user.nav')
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <h1>{{$post->title}}</h1>
                    <img width="100" src="{{$post->image}}" alt="">
                    <p>{{$post->text}}</p>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/profile/show.blade.php
@extends('layouts.app')

@php
    use App\Models\User;
    /** @var User $user */
@endphp

@section('content')
    <div class="container">
        @include('components.user.nav')

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    {{ html()->form('PUT')->route('profile.update', $user->id)->acceptsFiles()->open() }}

                    <div class='col-6 mb-3'>
                        @if ($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                        <label class="form-label" for="name">name</label>
                        {{ html()->input('text', 'name', $user->name)->id('name')->class('form-control form-control') }}
                    </div>

                    <div class='col-6 mb-3'>
                        @if ($errors->has('email'))
                            <span class="text-danger">{{ $errors->first('email') }}</span>
                        @endif
                        <label class="form-label" for="email">email</label>
                        {{ html()->input('email', 'email', $user->email)->id('email')->class('form-control form-control') }}
                    </div>

                    <div class='col-6 mb-3'>
                        @if ($errors->has('password'))
                            <span class="text-danger">{{ $errors->first('password') }}</span>
                        @endif
                        <label class="form-label" for="password">password</label>
                        {{ html()->input('password', 'password')->id('password')->class('form-control form-control') }}
                    </div>


                    <img width="50" src="{{asset($user->avatar)}}">

                    {{ html()->input('file', 'avatar') }}
                    <button type="submit">UPDATE</button>

                    {{ html()->form()->close() }}

                    <hr>
                    {{ html()->form('DELETE')->route('profile.destroy', $user->id)->open() }}
                    <button type="submit" class="text-danger">DELETE PROFILE</button>
                    {{ html()->form()->close() }}


                </div>
            </div>
        </div>
    </div>
@endsection